version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongo_db:
